#include "ADC1Dev.h"

void ADC1_Config(void)
{
  ADC1_DeInit();
  ADC1_Init(ADC1_CONVERSIONMODE_CONTINUOUS, ADC1_CHANNEL_0, ADC1_PRESSEL_FCPU_D4,
            ADC1_EXTTRIG_TIM, DISABLE, ADC1_ALIGN_RIGHT, ADC1_SCHMITTTRIG_CHANNEL0, DISABLE);
  //ADC1_ITConfig(ADC1_IT_AWS0, ENABLE);
  ADC1_Cmd(ENABLE);
  ADC1_StartConversion();
}